spring:
  h2.console:
    enabled: true
    path: '/console'

  jpa:
    hibernate:
      ddl-auto: validate

keycloak:
  auth-server-url: 'http://192.168.55.210:8180/auth/'
  realm: 'ContractorsApp'
  resource: 'contractors-spring-client'
  public-client: true
